### ISSUE TITLE
Cant get the app to work =(

### ISSUE THREAD

**Issue by jessemoon0** [codeschool/SequelToSQLSoupToBits#3]
NOTE: I have no knowledge of node or express.js so far
-I managed to install npm and node by package downloaded on web (when I put -v on both it shows me the version)
-I managed to install bower and gulp by doing sudo npm install bower gulp -g (when I put -v on both it shows me the version, in gulp says "CLI Version 3.9.0")
-I managed to do gem install compass (I have already installed ruby on rails) so no errors returned
-I managed to download to my Mac OSX 10.11 Desktop by git clone

The problem is when I try to install dependencies:

I put cd to the SequelToSQLSoupToBits folder and I do sudo npm install && bower install (I have tried without sudo, and install each one separately). When I try to install separately, bower shows me no errors but npm install shows me the following errors: 

![screen shot 2015-10-27 at 10 51 17 am](https://cloud.githubusercontent.com/assets/13438524/10765523/c24ba3b6-7c98-11e5-8be8-d2a4cdd962ca.png)
![screen shot 2015-10-27 at 10 50 16 am](https://cloud.githubusercontent.com/assets/13438524/10765524/c272520e-7c98-11e5-95b6-27d713b1f58a.png)
![screen shot 2015-10-27 at 10 51 31 am](https://cloud.githubusercontent.com/assets/13438524/10765526/c27a1822-7c98-11e5-8f38-3c87f8ddf522.png)
![screen shot 2015-10-27 at 10 51 43 am](https://cloud.githubusercontent.com/assets/13438524/10765525/c275a10c-7c98-11e5-99fa-aaf52dc7591a.png)

....

Can u help me fixing this? Thanks A LOT in advance!

Sincerely
Jessie

**Comment by Dobpbiu** [comment]
Same thing as in Jessie issue.

The error at the last stage: npm install && bower install

Tried on El Capitan 10.11.4 and on Ubuntu 15.10, result the same.

157286 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
157287 error node v5.11.0
157288 error npm  v3.8.6
157289 error code ELIFECYCLE
157290 error node-sass@0.9.6 install: `node build.js`
157290 error Exit status 1
157291 error Failed at the node-sass@0.9.6 install script 'node build.js'.
 
....

Sincerely
Ivan

**Comment by jonfriskics** [comment]
Hi all - I just tested and it looks like this was due to including a much older version of gulp-sass.  I updated the `package.json` file to load a newer version and after that the steps in the README are working fine for me.  Please re-open if you're seeing the same or similar problem after pulling down the update version of this repo.
